version: "3"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: "travel_agency_spring"
      POSTGRES_USER: "Oleh"
      POSTGRES_PASSWORD: "Oleh_Password"
    ports:
      - "8081:5432"
    volumes:
      - postgre_spring_volume:/var/lib/postgresql/data

volumes:
  postgre_spring_volume:
    driver: local
